spring.application.name=notification-service

# Server port
server.port=8085

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/notification_db

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

internal.token=b0af0f2eb861762c60666c4809d5e85fcf3f0150237c67b5020e051108f9d55d

spring.security.user.name=admin
spring.security.user.password=admin
